# Site settings
title: 'My Journey to a Data Storyteller'
description: 'Personal blog and portfolio exploring the world of data storytelling'
author: 'Wan-Ting Chang'
email: 'wantingchang.tw@gmail.com'

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Collections
collections:
    posts:
        output: true
        permalink: /:year/:month/:day/:title/

# Defaults
defaults:
    - scope:
          path: ''
          type: 'posts'
      values:
          layout: 'post'
    - scope:
          path: ''
      values:
          layout: 'default'

# Plugins
plugins:
    - jekyll-feed
    - jekyll-sitemap

# Exclude from processing
exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - vendor/
